title: SimpleReport
url: https://beta.simplereport.cdc.gov
dap_agency: HHS
dap_subagency: CDC
okta_url: https://hhs-prime.okta.com/oauth2/default/v1/authorize?client_id=0oa5ahrdfSpxmNZO74h6&amp;response_type=token+id_token&amp;scope=openid&amp;scope=simple_report&amp;redirect_uri=https://simplereport.cdc.gov/app&amp;nonce=thisisnotsafe&amp;state=thisisbogus

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - adr/
  - assets/js/src
  - config.json
  - Gemfile*
  - gemfiles/
  - gulpfile.js
  - node_modules
  - node_modules/
  - package-lock.json
  - package.json
  - package*.json
  - README.md
  - scripts/
  - vendor/
  - webpack.config.js
  - artifact/
  - artifact.zip
  - lighthouse
  - release-notes.txt
  - spec/
  - assets/js/uswds.js
  - webpack/
