title: SimpleReport
url: https://dev.simplereport.cdc.gov
dap_agency: HHS
dap_subagency: CDC
okta_url: https://hhs-prime.okta.com/oauth2/default/v1/authorize?client_id=0oa61vdmqd56921Ka4h6&redirect_uri=https://dev.simplereport.gov/app&response_type=token+id_token&scope=openid%20simple_report%20simple_report_dev&nonce=thisisnotsafe&state=thisisbogus

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - adr/
  - assets/js/src
  - config.json
  - Gemfile*
  - gemfiles/
  - gulpfile.js
  - node_modules
  - node_modules/
  - package-lock.json
  - package.json
  - package*.json
  - README.md
  - scripts/
  - vendor/
  - webpack.config.js
  - artifact/
  - artifact.zip
  - lighthouse
  - release-notes.txt
  - spec/
  - assets/js/uswds.js
  - webpack/
