title: SimpleReport
baseurl: /SimpleReport_Public_Site
url: http://cdcgov.github.io
dap_agency: HHS
dap_subagency: CDC

plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - adr/
  - assets/js/src
  - config.json
  - Gemfile*
  - gemfiles/
  - gulpfile.js
  - node_modules
  - node_modules/
  - package-lock.json
  - package.json
  - package*.json
  - README.md
  - scripts/
  - vendor/
  - webpack.config.js
  - artifact/
  - artifact.zip
  - lighthouse
  - release-notes.txt
  - spec/
  - assets/js/uswds.js
  - webpack/
