name: Run end-to-end tests

on: pull_request

defaults:
  run:
    working-directory: .

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: Cache npm local files
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules
          key: npm-${{matrix.node}}-${{ hashFiles('yarn.lock', 'package.json') }}
      - name: Install node modules
        run: npm install
      - name: Setup site
        run: |
          npm run setup
      - name: Serve site
        run: npm run serve:e2e &
      - name: Setup firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: latest
      - name: Run nightwatch
        run: npm run e2e
