name: Run Lighthouse

on:
  push:
    branches:
      - gh-pages
      - main
jobs:
  validate-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lighthouse CI Action
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            $SITE_URL/
            $SITE_URL/sign-up/
          uploadArtifacts: true
          configPath: ./lighthouse/lighthouserc.yml
          runs: 1
        env:
          SITE_URL: https://cdcgov.github.io/prime-simplereport-site
  # eslint:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Node
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: '12.x'
  #   - name: Install eslint plugins
  #     run: npm install eslint-plugin-frontmatter@latest --save-dev
  #   - name: Install eslint
  #     run: npm i -g eslint
  #   - name: Run es-lint
  #     run: eslint assets/js/
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install rubocop
        run: gem install rubocop
      - name: Run rubocop
        run: rubocop
